set -e
true
true
/data/homezvol3/delmundz/.conda/envs/spades_env/bin/spades-core /pub/delmundz/EE283/HW4/A5/assembly/K21/configs/config.info /pub/delmundz/EE283/HW4/A5/assembly/K21/configs/isolate_mode.info
/data/homezvol3/delmundz/.conda/envs/spades_env/bin/spades-core /pub/delmundz/EE283/HW4/A5/assembly/K33/configs/config.info /pub/delmundz/EE283/HW4/A5/assembly/K33/configs/isolate_mode.info
/data/homezvol3/delmundz/.conda/envs/spades_env/bin/python /data/homezvol3/delmundz/.conda/envs/spades_env/share/spades/spades_pipeline/scripts/copy_files.py /pub/delmundz/EE283/HW4/A5/assembly/K33/before_rr.fasta /pub/delmundz/EE283/HW4/A5/assembly/before_rr.fasta /pub/delmundz/EE283/HW4/A5/assembly/K33/assembly_graph_after_simplification.gfa /pub/delmundz/EE283/HW4/A5/assembly/assembly_graph_after_simplification.gfa /pub/delmundz/EE283/HW4/A5/assembly/K33/final_contigs.fasta /pub/delmundz/EE283/HW4/A5/assembly/contigs.fasta /pub/delmundz/EE283/HW4/A5/assembly/K33/first_pe_contigs.fasta /pub/delmundz/EE283/HW4/A5/assembly/first_pe_contigs.fasta /pub/delmundz/EE283/HW4/A5/assembly/K33/strain_graph.gfa /pub/delmundz/EE283/HW4/A5/assembly/strain_graph.gfa /pub/delmundz/EE283/HW4/A5/assembly/K33/scaffolds.fasta /pub/delmundz/EE283/HW4/A5/assembly/scaffolds.fasta /pub/delmundz/EE283/HW4/A5/assembly/K33/scaffolds.paths /pub/delmundz/EE283/HW4/A5/assembly/scaffolds.paths /pub/delmundz/EE283/HW4/A5/assembly/K33/assembly_graph_with_scaffolds.gfa /pub/delmundz/EE283/HW4/A5/assembly/assembly_graph_with_scaffolds.gfa /pub/delmundz/EE283/HW4/A5/assembly/K33/assembly_graph.fastg /pub/delmundz/EE283/HW4/A5/assembly/assembly_graph.fastg /pub/delmundz/EE283/HW4/A5/assembly/K33/final_contigs.paths /pub/delmundz/EE283/HW4/A5/assembly/contigs.paths
true
/data/homezvol3/delmundz/.conda/envs/spades_env/bin/python /data/homezvol3/delmundz/.conda/envs/spades_env/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /pub/delmundz/EE283/HW4/A5/assembly/scaffolds.fasta --misc_dir /pub/delmundz/EE283/HW4/A5/assembly/misc --threshold_for_breaking_scaffolds 3
true
